# Generated by OpenCode on 2026-03-23

import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0003_alter_workspaceuserresourcepermission_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="修改时间"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="主键id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="工作空间名称",
                    ),
                ),
            ],
            options={
                "db_table": "workspace",
                "ordering": ["create_time"],
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model(
                "system_manage", "Workspace"
            ).objects.get_or_create(id="default", defaults={"name": "default"}),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
