from django.urls import path

from . import views

app_name = "knowledge"
# @formatter:off
urlpatterns = [
    path(
        "system/resource/knowledge/<int:current_page>/<int:page_size>",
        views.SystemResourceKnowledgeView.Page.as_view(),
    ),
    path(
        "system/resource/knowledge/<str:knowledge_id>/export",
        views.SystemResourceKnowledgeView.Export.as_view(),
    ),
    path(
        "system/resource/knowledge/<str:knowledge_id>/export_zip",
        views.SystemResourceKnowledgeView.ExportZip.as_view(),
    ),
    path(
        "system/resource/knowledge/<str:knowledge_id>/embedding",
        views.SystemResourceKnowledgeView.Embedding.as_view(),
    ),
    path(
        "system/resource/knowledge/<str:knowledge_id>/hit_test",
        views.SystemResourceKnowledgeView.HitTest.as_view(),
    ),
    path(
        "system/resource/knowledge/<str:knowledge_id>/generate_related",
        views.SystemResourceKnowledgeView.GenerateRelated.as_view(),
    ),
    path(
        "system/resource/knowledge/<str:knowledge_id>/sync",
        views.SystemResourceKnowledgeView.SyncWeb.as_view(),
    ),
    path(
        "system/resource/knowledge/<str:knowledge_id>/document/<int:current_page>/<int:page_size>",
        views.SystemResourceDocumentView.Page.as_view(),
    ),
    path(
        "system/resource/knowledge/<str:knowledge_id>/document/<str:document_id>/export",
        views.SystemResourceDocumentView.Export.as_view(),
    ),
    path(
        "system/resource/knowledge/<str:knowledge_id>/document/<str:document_id>/export_zip",
        views.SystemResourceDocumentView.ExportZip.as_view(),
    ),
    path(
        "system/resource/knowledge/<str:knowledge_id>/document/<str:document_id>/refresh",
        views.SystemResourceDocumentView.Refresh.as_view(),
    ),
    path(
        "system/resource/knowledge/<str:knowledge_id>/document/<str:document_id>/sync",
        views.SystemResourceDocumentView.Sync.as_view(),
    ),
    path(
        "system/resource/knowledge/<str:knowledge_id>/document/<str:document_id>/cancel_task",
        views.SystemResourceDocumentView.CancelTask.as_view(),
    ),
    path(
        "system/resource/knowledge/<str:knowledge_id>/document/<str:document_id>",
        views.SystemResourceDocumentView.Operate.as_view(),
    ),
    path(
        "system/resource/knowledge/<str:knowledge_id>",
        views.SystemResourceKnowledgeView.Operate.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/KNOWLEDGE/<str:resource_id>/user_group",
        views.WorkspaceKnowledgeChatUserGroupView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/KNOWLEDGE/<str:resource_id>/user_group_id/<str:user_group_id>/<int:current_page>/<int:page_size>",
        views.WorkspaceKnowledgeChatUserGroupUserView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/KNOWLEDGE/<str:resource_id>/user_group_id/<str:user_group_id>",
        views.WorkspaceKnowledgeChatUserGroupUserView.as_view(),
    ),
    path(
        "system/resource/KNOWLEDGE/<str:resource_id>/user_group",
        views.SystemKnowledgeChatUserGroupView.as_view(),
    ),
    path(
        "system/resource/KNOWLEDGE/<str:resource_id>/user_group_id/<str:user_group_id>/<int:current_page>/<int:page_size>",
        views.SystemKnowledgeChatUserGroupUserView.as_view(),
    ),
    path(
        "system/resource/KNOWLEDGE/<str:resource_id>/user_group_id/<str:user_group_id>",
        views.SystemKnowledgeChatUserGroupUserView.as_view(),
    ),
    path("workspace/knowledge/document/template/export", views.Template.as_view()),
    path(
        "workspace/knowledge/document/table_template/export",
        views.TableTemplate.as_view(),
    ),
    path(
        "workspace/store/knowledge_template",
        views.KnowledgeView.StoreKnowledge.as_view(),
    ),
    path("workspace/<str:workspace_id>/knowledge", views.KnowledgeView.as_view()),
    path(
        "workspace/<str:workspace_id>/knowledge/base", views.KnowledgeBaseView.as_view()
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/workflow",
        views.KnowledgeWorkflowView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/web", views.KnowledgeWebView.as_view()
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/lark/save",
        views.KnowledgeLarkView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/lark/<str:knowledge_id>",
        views.KnowledgeLarkView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/model",
        views.KnowledgeView.Model.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/embedding_model",
        views.KnowledgeView.EmbeddingModel.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/tags",
        views.KnowledgeView.Tags.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>",
        views.KnowledgeView.Operate.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/sync",
        views.KnowledgeView.SyncWeb.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/workflow",
        views.KnowledgeWorkflowView.Operate.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/workflow/export",
        views.KnowledgeWorkflowView.Export.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/workflow/import",
        views.KnowledgeWorkflowView.Import.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/generate_related",
        views.KnowledgeView.GenerateRelated.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/embedding",
        views.KnowledgeView.Embedding.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/hit_test",
        views.KnowledgeView.HitTest.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/export",
        views.KnowledgeView.Export.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/export_zip",
        views.KnowledgeView.ExportZip.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/transform_workflow",
        views.KnowledgeView.TransformWorkflow.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/tags",
        views.KnowledgeTagView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/tags/batch_delete",
        views.KnowledgeTagView.BatchDelete.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/tags/<str:tag_id>",
        views.KnowledgeTagView.Operate.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/tags/<str:tag_id>/<str:delete_type>",
        views.KnowledgeTagView.Delete.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document",
        views.DocumentView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/split",
        views.DocumentView.Split.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/split_pattern",
        views.DocumentView.SplitPattern.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/batch_create",
        views.DocumentView.BatchCreate.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/batch_sync",
        views.DocumentView.BatchSync.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/batch_delete",
        views.DocumentView.BatchDelete.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/batch_refresh",
        views.DocumentView.BatchRefresh.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/batch_generate_related",
        views.DocumentView.BatchGenerateRelated.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/batch_export",
        views.DocumentView.BatchExport.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/batch_export_zip",
        views.DocumentView.BatchExportZip.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/web",
        views.WebDocumentView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/lark/<str:knowledge_id>/<str:folder_token>/doc_list",
        views.LarkDocumentListView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/lark/<str:knowledge_id>/import",
        views.LarkDocumentImportView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/qa",
        views.QaDocumentView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/table",
        views.TableDocumentView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/batch_hit_handling",
        views.DocumentView.BatchEditHitHandling.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/batch_cancel_task",
        views.DocumentView.BatchCancelTask.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/batch_add_tag",
        views.DocumentView.BatchAddTag.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/migrate/<str:target_knowledge_id>",
        views.DocumentView.Migrate.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>",
        views.DocumentView.Operate.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/sync",
        views.DocumentView.SyncWeb.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/refresh",
        views.DocumentView.Refresh.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/cancel_task",
        views.DocumentView.CancelTask.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/export",
        views.DocumentView.Export.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/export_zip",
        views.DocumentView.ExportZip.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/download_source_file",
        views.DocumentView.DownloadSourceFile.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/replace_source_file",
        views.DocumentView.ReplaceSourceFile.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/tags",
        views.DocumentView.Tags.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/tags/batch_delete",
        views.DocumentView.Tags.BatchDelete.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/tag/<str:tag_id>/docs_delete",
        views.DocumentView.Tags.BatchDeleteDocsTag.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/paragraph",
        views.ParagraphView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/paragraph/batch_delete",
        views.ParagraphView.BatchDelete.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/paragraph/batch_generate_related",
        views.ParagraphView.BatchGenerateRelated.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/paragraph/migrate/knowledge/<str:target_knowledge_id>/document/<str:target_document_id>",
        views.ParagraphView.BatchMigrate.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/paragraph/association",
        views.ParagraphView.Association.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/paragraph/unassociation",
        views.ParagraphView.UnAssociation.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/paragraph/adjust_position",
        views.ParagraphView.AdjustPosition.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/paragraph/<str:paragraph_id>",
        views.ParagraphView.Operate.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/paragraph/<str:paragraph_id>/problem",
        views.ParagraphView.Problem.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/paragraph/<int:current_page>/<int:page_size>",
        views.ParagraphView.Page.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/problem",
        views.ProblemView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/problem/batch_delete",
        views.ProblemView.BatchDelete.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/problem/batch_association",
        views.ProblemView.BatchAssociation.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/problem/<str:problem_id>",
        views.ProblemView.Operate.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/problem/<str:problem_id>/paragraph",
        views.ProblemView.Paragraph.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/problem/<int:current_page>/<int:page_size>",
        views.ProblemView.Page.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/document/<int:current_page>/<int:page_size>",
        views.DocumentView.Page.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<int:current_page>/<int:page_size>",
        views.KnowledgeView.Page.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/datasource/<str:type>/<str:id>/form_list",
        views.KnowledgeDatasourceFormListView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/datasource/<str:type>/<str:id>/<str:function_name>",
        views.KnowledgeDatasourceView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/publish",
        views.KnowledgeWorkflowView.Publish.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/debug",
        views.KnowledgeWorkflowActionView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/action/<int:current_page>/<int:page_size>",
        views.KnowledgeWorkflowActionView.Page.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/upload_document",
        views.KnowledgeWorkflowUploadDocumentView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/action/<str:knowledge_action_id>",
        views.KnowledgeWorkflowActionView.Operate.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/action/<str:knowledge_action_id>/cancel",
        views.KnowledgeWorkflowActionView.Cancel.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/mcp_tools",
        views.McpServers.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/knowledge_version",
        views.KnowledgeWorkflowVersionView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/knowledge_version/<int:current_page>/<int:page_size>",
        views.KnowledgeWorkflowVersionView.Page.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/knowledge/<str:knowledge_id>/knowledge_version/<str:knowledge_version_id>",
        views.KnowledgeWorkflowVersionView.Operate.as_view(),
    ),
]
