from django.urls import path

from . import views

app_name = "application"
# @formatter:off
urlpatterns = [
    path(
        "system/resource/application",
        views.SystemResourceApplicationView.as_view(),
    ),
    path(
        "system/resource/application/<int:current_page>/<int:page_size>",
        views.SystemResourceApplicationView.Page.as_view(),
    ),
    path(
        "workspace/store/application_template",
        views.ApplicationAPI.StoreApplication.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application",
        views.ApplicationAPI.as_view(),
        name="application",
    ),
    path(
        "workspace/<str:workspace_id>/application/folder/<str:folder_id>/import",
        views.ApplicationAPI.Import.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<int:current_page>/<int:page_size>",
        views.ApplicationAPI.Page.as_view(),
        name="application_page",
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>",
        views.ApplicationAPI.Operate.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/publish",
        views.ApplicationAPI.Publish.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/move/<str:folder_id>",
        views.ApplicationAPI.Move.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/application_key",
        views.ApplicationKey.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/application_stats",
        views.ApplicationStats.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/application_token_usage",
        views.ApplicationStats.TokenUsageStatistics.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/top_questions",
        views.ApplicationStats.TopQuestionsStatistics.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/application_key/<str:api_key_id>",
        views.ApplicationKey.Operate.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/application_key/<int:current_page>/<int:page_size>",
        views.ApplicationKey.Page.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/export",
        views.ApplicationAPI.Export.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/application_version",
        views.ApplicationVersionView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/access_token",
        views.AccessToken.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/platform/status",
        views.WorkspaceApplicationPlatformStatusView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/platform/<str:platform_type>",
        views.WorkspaceApplicationPlatformConfigView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/platform/status",
        views.SystemResourceApplicationPlatformStatusView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/platform/<str:platform_type>",
        views.SystemResourceApplicationPlatformConfigView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/access_token",
        views.SystemResourceApplicationAccessTokenView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/setting",
        views.SystemResourceApplicationSettingView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/open",
        views.SystemResourceApplicationOpenView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/play_demo_text",
        views.SystemResourceApplicationPlayDemoTextView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/text_to_speech",
        views.SystemResourceApplicationTextToSpeechView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/speech_to_text",
        views.SystemResourceApplicationSpeechToTextView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/mcp_tools",
        views.SystemResourceApplicationMcpToolsView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/application_version",
        views.SystemResourceApplicationVersionView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/application_version/<str:application_version_id>",
        views.SystemResourceApplicationVersionView.Operate.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/model/<str:model_id>/prompt_generate",
        views.SystemResourceApplicationPromptGenerateView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/application_key",
        views.SystemResourceApplicationKeyView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/application_key/<str:api_key_id>",
        views.SystemResourceApplicationKeyView.Operate.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/application_key/<int:current_page>/<int:page_size>",
        views.SystemResourceApplicationKeyView.Page.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/export",
        views.SystemResourceApplicationExportView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/application_stats",
        views.SystemResourceApplicationStatsView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/application_token_usage",
        views.SystemResourceApplicationStatsView.TokenUsageStatistics.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/top_questions",
        views.SystemResourceApplicationStatsView.TopQuestionsStatistics.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/publish",
        views.SystemResourceApplicationPublishView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>",
        views.SystemResourceApplicationOperateView.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/chat/export",
        views.SystemResourceApplicationChat.Export.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/add_knowledge",
        views.SystemResourceApplicationChatRecordAddKnowledge.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/chat/<str:chat_id>/chat_record/<str:chat_record_id>/improve",
        views.SystemResourceApplicationChatRecordImprove.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/chat/<str:chat_id>/chat_record/<str:chat_record_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/improve",
        views.SystemResourceApplicationChatRecordImproveParagraph.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/chat/<str:chat_id>/chat_record/<str:chat_record_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/paragraph/<str:paragraph_id>/improve",
        views.SystemResourceApplicationChatRecordImproveParagraph.Operate.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/chat/<int:current_page>/<int:page_size>",
        views.SystemResourceApplicationChat.Page.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/chat/<str:chat_id>/chat_record/<str:chat_record_id>",
        views.SystemResourceApplicationChatRecordOperate.as_view(),
    ),
    path(
        "system/resource/application/<str:application_id>/chat/<str:chat_id>/chat_record/<int:current_page>/<int:page_size>",
        views.SystemResourceApplicationChatRecord.Page.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/<str:resource_type>/<str:resource_id>/user_group",
        views.WorkspaceApplicationChatUserGroupView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/<str:resource_type>/<str:resource_id>/user_group_id/<str:user_group_id>/<int:current_page>/<int:page_size>",
        views.WorkspaceApplicationChatUserGroupUserView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/<str:resource_type>/<str:resource_id>/user_group_id/<str:user_group_id>",
        views.WorkspaceApplicationChatUserGroupUserView.as_view(),
    ),
    path(
        "system/resource/<str:resource_type>/<str:resource_id>/user_group",
        views.SystemApplicationChatUserGroupView.as_view(),
    ),
    path(
        "system/resource/<str:resource_type>/<str:resource_id>/user_group_id/<str:user_group_id>/<int:current_page>/<int:page_size>",
        views.SystemApplicationChatUserGroupUserView.as_view(),
    ),
    path(
        "system/resource/<str:resource_type>/<str:resource_id>/user_group_id/<str:user_group_id>",
        views.SystemApplicationChatUserGroupUserView.as_view(),
    ),
    path("chat_user/auth/types", views.ChatUserAuthTypeView.as_view()),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/add_knowledge",
        views.ApplicationChatRecordAddKnowledge.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/chat",
        views.ApplicationChat.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/chat/export",
        views.ApplicationChat.Export.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/chat/<int:current_page>/<int:page_size>",
        views.ApplicationChat.Page.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/chat/<str:chat_id>/chat_record",
        views.ApplicationChatRecord.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/chat/<str:chat_id>/chat_record/<str:chat_record_id>",
        views.ApplicationChatRecordOperateAPI.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/chat/<str:chat_id>/chat_record/<int:current_page>/<int:page_size>",
        views.ApplicationChatRecord.Page.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/chat/<str:chat_id>/chat_record/<str:chat_record_id>/improve",
        views.ApplicationChatRecordImprove.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/chat/<str:chat_id>/chat_record/<str:chat_record_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/improve",
        views.ApplicationChatRecordImproveParagraph.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/chat/<str:chat_id>/chat_record/<str:chat_record_id>/knowledge/<str:knowledge_id>/document/<str:document_id>/paragraph/<str:paragraph_id>/improve",
        views.ApplicationChatRecordImproveParagraph.Operate.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/application_version/<int:current_page>/<int:page_size>",
        views.ApplicationVersionView.Page.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/application_version/<str:application_version_id>",
        views.ApplicationVersionView.Operate.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/open",
        views.OpenView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/text_to_speech",
        views.TextToSpeech.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/speech_to_text",
        views.SpeechToText.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/play_demo_text",
        views.PlayDemoText.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/mcp_tools",
        views.McpServers.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/orchestrator_integration",
        views.OrchestratorIntegrationConfigView.as_view(),
    ),
    path(
        "workspace/<str:workspace_id>/application/<str:application_id>/model/<str:model_id>/prompt_generate",
        views.PromptGenerateView.as_view(),
    ),
    path("chat_message/<str:chat_id>", views.ChatView.as_view()),
]
